### ISSUE TITLE
Invalid get_string() identifier

### ISSUE THREAD

**Issue by eduardokraus** [mebis-lp/moodle-local_ai_manager#24]
Invalid get_string() identifier: 'subplugintype_aitool' or component 'local_ai_manager'. Perhaps you are missing $string['subplugintype_aitool'] = ''; in /local/ai_manager/lang/en/local_ai_manager.php?
* line 356 of /lib/classes/string_manager_standard.php: call to debugging()
* line 7009 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
* line 624 of /lib/classes/plugin_manager.php: call to get_string()
* line 130 of /admin/tool/installaddon/classes/installer.php: call to core\plugin_manager->plugintype_name()
* line 54 of /admin/tool/installaddon/classes/installfromzip_form.php: call to tool_installaddon_installer->get_plugin_types_menu()
* line 217 of /lib/formslib.php: call to tool_installaddon_installfromzip_form->definition()
* line 100 of /admin/tool/installaddon/classes/installer.php: call to moodleform->__construct()
* line 93 of /admin/tool/installaddon/index.php: call to tool_installaddon_installer->get_installfromzip_form()
* Invalid get_string() identifier: 'subplugintype_aipurpose' or component 'local_ai_manager'. Perhaps you are missing 

$string['subplugintype_aipurpose'] = ''; in /local/ai_manager/lang/en/local_ai_manager.php?
* line 356 of /lib/classes/string_manager_standard.php: call to debugging()
* line 7009 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
* line 624 of /lib/classes/plugin_manager.php: call to get_string()
* line 130 of /admin/tool/installaddon/classes/installer.php: call to core\plugin_manager->plugintype_name()
* line 54 of /admin/tool/installaddon/classes/installfromzip_form.php: call to tool_installaddon_installer->get_plugin_types_menu()
* line 217 of /lib/formslib.php: call to tool_installaddon_installfromzip_form->definition()
* line 100 of /admin/tool/installaddon/classes/installer.php: call to moodleform->__construct()
* line 93 of /admin/tool/installaddon/index.php: call to tool_installaddon_installer->get_installfromzip_form()

**Comment by PhMemmel** [comment]
Thanks for the report. While it's quite obvious how this has to be fixed (and it will be shortly), would you mind sharing how to reproduce this debugging message? Thanks in advance.

**Comment by eduardokraus** [comment]
Logged in as an administrator, I’m receiving the following message on all administration screens:

The two strings refer to the names of the sub-plugins of my plugin. The first, "subplugintype_aipurpose," is related to the "aipurpose" sub-plugins, while the second, "subplugintype_aitool," refers to the "aitool" sub-plugins. It seems the system is trying to identify and connect these two categories of sub-plugins, but something in the configuration or code is causing this notification to appear on all admin pages.

**Comment by PhMemmel** [comment]
Thank you for the feedback. It does not appear on all sites for me, but only when trying to install a plugin (`/admin/tool/installaddon/index.php`). I pushed the missing strings into the main branch.
