### ISSUE TITLE
Privacy API implementation

### ISSUE THREAD

**Issue by volodymyrdovhan** [mebis-lp/moodle-local_ai_manager#32]
Hello,
please fully implement Privacy API as the plugin stores userid in tables.
You can verify implementation with CLI scripts: https://moodledev.io/docs/4.5/apis/subsystems/privacy/utils

![image](https://github.com/user-attachments/assets/9e04a766-1ebd-4efc-8bdd-6076e1035f81)
![image](https://github.com/user-attachments/assets/1707bb7d-06ba-4476-a5d6-bc0d15938ae7)

**Comment by PhMemmel** [comment]
dup of #10
