### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by volodymyrdovhan** [mebis-lp/moodle-local_ai_manager#33]
Hello,
I found places with not defined strings in lang file:
![image](https://github.com/user-attachments/assets/466a3eca-89be-4ec3-baa8-264797fa6aa9)
![image](https://github.com/user-attachments/assets/c6af9042-9706-4438-af07-6efbe0d764dd)

**Comment by PhMemmel** [comment]
Has been fixed by 00c7d2c0bbe6e66fecfc809e245c7f6d3d493063 and #27
